name: core_pmc
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: ^3.8.1

dependencies:
  sentry_flutter: ^9.7.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.0
  package_info_plus: ^8.3.0
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  card_swiper: ^3.0.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  file_picker: ^10.3.1
  google_maps_flutter: ^2.12.3
  google_places_flutter: ^2.1.1
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  flutter_contacts: ^1.1.9+2
  dio: ^5.9.0
  path_provider: ^2.1.5
  fl_downloader: ^2.1.0
  flutter_downloader: ^1.12.0
  provider: ^6.1.5+1
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.1
  flutter_launcher_icons: ^0.14.4
  smooth_compass_new: ^0.0.4
  cloud_firestore: ^6.0.1
  fl_chart: ^1.1.0
  social_sharing_plus: ^1.2.3
  share_plus: ^12.0.1
  audioplayers: ^6.5.1

dev_dependencies:
  sentry_dart_plugin: ^3.1.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/svg/
    - assets/icon/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Lexend-Black.ttf
          weight: 900
        - asset: assets/fonts/Lexend-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Lexend-Thin.ttf
          weight: 100
sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: corepmc
  org: excellence-it-solution
